version: '3.4'

services:
  myfirstapp:
    image: myfirstapp
    build:
      context: my-first-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3030:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
