version: '3.4'

services:
  myfirstapp:
    image: myfirstapp
    build:
      context: my-first-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
